name: gebyarpajak
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  audioplayers: ^5.2.1
  carousel_slider: ^5.0.0
  chewie: ^1.7.4
  cupertino_icons: ^1.0.2
  easy_debounce: ^2.0.3
  flutter:
    sdk: flutter
  get: 4.6.6
  sizer: ^2.0.15
  video_player: ^2.8.1

dev_dependencies:
  flutter_lints: 3.0.1
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/images/
    - assets/sounds/
  uses-material-design: true
